services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555" # Prisma Studio用のポートを公開
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/taskautomatic"
      CHOKIDAR_USEPOLLING: true
      NEXT_DEV_PORT: 3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskautomatic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
