services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
      - "5555:5555" # Prisma Studio用のポートを公開
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/taskautomatics?schema=public"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskautomatic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "taskautomatic"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: